config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
    get '/login' => 'login#login', :as => :login
    get '/login/google', to: redirect('auth/google_oauth2'), as: :google_login
    get '/login/github', to: redirect('auth/github'), as: :github_login
    get '/auth/google_oauth2/callback', to: 'login#google_oauth2', as: :google_oauth2_callback
    get '/auth/github/callback', to: 'login#github', as: :github_callback
    get '/logout' => 'login#logout', :as => :logout
    get '/user/profile', to: 'user#profile', as: :user_profile

    root to: 'map#index', as: 'root'
    get '/state/:state_symbol' => 'map#state', :as => :state_map
    get '/state/:state_symbol/county/:std_fips_code' => 'map#county', :as => :county

    get '/ajax/state/:state_symbol' => 'ajax#counties'

    # Routes for Events
    resources :events, only: %i[index show]
    get '/my_events/new' => 'my_events#new', :as => :new_my_event
    match '/my_events/new', to: 'my_events#create', via: [:post]
    get '/my_events/:id' => 'my_events#edit', :as => :edit_my_event
    match '/my_events/:id', to: 'my_events#update', via: %i[put patch]
    match '/my_events/:id', to: 'my_events#destroy', via: [:delete]

    # Routes for Representatives
    resources :representatives, only: [:index]
    resources :representatives do
        resources :news_items, only: %i[index show]
        get '/representatives/:representative_id/my_news_item/new' => 'my_news_items#new',
            :as                                                    => :new_my_news_item
        post '/representatives/:representative_id/my_news_item/new' => 'my_news_items#create',
        :as                                                    => :create_my_news_item
        get '/representatives/:representative_id/my_news_item/top_articles' => 'my_news_items#news_with_api',
            :as                                                    => :top_articles
        match '/representatives/:representative_id/my_news_item/top_articles', to:  'my_news_items#create',
                                                                      via: [:post]
        get '/representatives/:representative_id/my_news_item/:id' => 'my_news_items#edit',
            :as                                                    => :edit_my_news_item
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#update',
                                                                      via: %i[put patch]
        match '/representatives/:representative_id/my_news_item/:id', to:  'my_news_items#destroy',
                                                                      via: [:delete]
    end
    get '/search/(:address)' => 'search#search', :as => 'search_representatives'
end

app/controllers/my_news_items_controller.rb
# frozen_string_literal: true

require 'httparty'

class MyNewsItemsController < SessionController
  before_action :set_representative
  before_action :set_representatives_list, :set_issues_list
  before_action :set_news_item, only: %i[edit update destroy]

  def new
    @news_item = NewsItem.new
  end

  def edit; end

  def create
    @news_item = NewsItem.new(news_item_params)

    if @news_item.save
      @representative.news_items << @news_item # added for task 2.1: to make news items get displayed in index
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully created.'
    else
      render :new, error: 'An error occurred when creating the news item.'
    end
  end

  def update
    if @news_item.update(news_item_params)
      redirect_to representative_news_item_path(@representative, @news_item),
                  notice: 'News item was successfully updated.'
    else
      render :edit, error: 'An error occurred when updating the news item.'
    end
  end

  def destroy
    @news_item.destroy
    redirect_to representative_news_items_path(@representative),
                notice: 'News was successfully destroyed.'
  end

  # part 2.2
  def news_with_api
    @representative = Representative.find(params[:news_item][:representative_id])
    news_key = Rails.application.credentials[:NEWS_API_KEY]

    # replaced by mock data, for the news api have limited requests
    query_hash = {
      apiKey:   news_key,
      q:        "#{@representative.name} #{news_item_params[:issue]}",
      sortBy:   'publishedAt',
      pageSize: 5
    }
    response = HTTParty.get('https://newsapi.org/v2/everything', { query: query_hash })

    news_data = JSON.parse(response.body)

    @articles = news_data['articles']

    render('top_articles')
  end

  private

  def set_representative
    @representative = Representative.find(
      params[:representative_id]
    )
  end

  def set_representatives_list
    @representatives_list = Representative.all.map { |r| [r.name, r.id] }
  end

  def set_news_item
    @news_item = NewsItem.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_item_params
    params.require(:news_item).permit(:news, :title, :description, :link, :representative_id, :issue, :rating)
  end

  def set_issues_list
    @issues_list = ['Free Speech', 'Immigration', 'Terrorism', 'Social Security and Medicare',
                    'Abortion', 'Student Loans', 'Gun Control', 'Unemployment',
                    'Climate Change', 'Homelessness', 'Racism', 'Tax Reform', 'Net Neutrality',
                    'Religious Freedom', 'Border Security', 'Minimum Wage', 'Equal Pay']
  end
end

app/views/my_news_items/_form.html.haml
= form_for news_item, url: form_url, html: { method: form_method } do |f|
    - if news_item.errors.any?
        .alert.alert-danger
            %h2
                "#{pluralize(news_item.errors.count, 'error')} prohibited this news from being saved:"
            %ul
                - news_item.errors.full_messages.each do |message|
                    %li= message
    .form-group.row
        .col-sm-2
            = label :news_item, :representative_id, class: 'col-form-label'
        .col-sm-10
            = select :news_item, :representative_id, representatives_list, { include_blank: true },
            class: 'form-control'
    .form-group.row
        .col-sm-2
            = label :news_item, :issue, 'Issue:', class: 'col-form-label'
        .col-sm-10
            = select :news_item, :issue, issues_list, { include_blank: true },
            class: 'form-control'
    .actions
        = f.submit 'Search', class: 'btn btn-primary'

app/views/my_news_items/add.html.erb
<h1>Top 5 News for <%= @representative.name %></h1>

<% @articles.each do |article| %>
  <div>
    <h2><%= article[:title] %></h2>
    <p><%= article[:description] %></p>
    <p><strong>Published At:</strong> <%= article['publishedAt'] %></p>
    <p><strong>URL:</strong> <%= link_to 'Read more', article['url'], target: '_blank' %></p>
    <hr>
  </div>
<<<<<<< HEAD:app/views/my_news_items/show_news.html.erb
<% end %>
=======
<% end %>

<%= form_with(url: representative_new_my_news_item_path(@representative), method: "post") do |form| %>
  <fieldset>
    <legend>Select an article:</legend>
    <% @articles.each_with_index do |article, index| %>
      <div>
        <%= form.radio_button :selected_article_index, index %>
        <%= form.label :selected_article_index, article['title'] %>
        <%= link_to 'Read more', article['url'], target: '_blank' %>

        <!-- Updated hidden fields to nest under the news_item key -->
        <%= form.hidden_field "news_item[title]", value: article['title'] %>
        <%= form.hidden_field "news_item[description]", value: article['description'] %>
        <%= form.hidden_field "news_item[url]", value: article['url'] %>
        <hr>
      </div>
    <% end %>
  </fieldset>

  <div>
    <%= form.label :rating, 'Rating' %>
    <%= form.select :rating, options_for_select([1, 2, 3, 4, 5]) %>
  </div>

  <%= form.submit "Save" %>
<% end %>
>>>>>>> a8947e64fb59cc9a60d61023c33fc1f35712235e:app/views/my_news_items/add.html.erb

app/views/my_news_items/edit.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
         form_url: representative_edit_my_news_item_path(@representative, @news_item),
         form_method: :put,
         representatives_list: @representatives_list,
         issues_list: @issues_list

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_item_path(@news_item), class: 'mx-1 btn btn-info' do
                    Show article
                    %i.fas.fa-eye
                = link_to representative_news_items_path(@representative), class: 'mx-1 btn btn-info' do
                    View all news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/new.html.haml
.row.mt-2
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        %h1.text-center Edit news article

    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        = render 'form', news_item: @news_item,
        form_url: representative_top_articles_path(@representative),
        form_method: :get,
        representatives_list: @representatives_list,
        issues_list: @issues_list
    .col-12.col-md-6.offset-md-3.col-xl-4.offset-xl-4
        .clearfix.mt-3
            .float-right
                = link_to representative_news_items_path(@representative), class: 'btn btn-info' do
                    View news articles
                    %i.fas.fa-arrow-right

app/views/my_news_items/top_articles.html.erb
<center>
<h1>Edit News Item</h1>
</center>

<body style="margin: 50px;">
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">

<h2>Representative: <%= link_to @representative.name, representative_path(@representative) %></h2>
<h2>Issue: <%= params[:news_item][:issue] %></h2>


<%= form_with(url: representative_create_my_news_item_path(@representative), method: "post") do |form| %>
  <fieldset>
    <legend>Select an article:</legend>
    <% @articles.each_with_index do |article, index| %>
      <div>
        <%= form.radio_button :articleindex, index, id: "article#{index}" %>
        <%= form.label "article_#{index}" do %>
          <strong>Title:</strong> <%= article['title'] %><br>
          <strong>Link:</strong><%= link_to article['url'], article['url'], target: '_blank' %><br>
          <strong>Description:</strong> <%= article['description'] %><br>
        <% end %>

        <!-- Hidden fields to store article attributes -->
        <%= form.hidden_field "news_item[title]", value: article['title'] %>
        <%= form.hidden_field "news_item[description]", value: article['description'] %>
        <%= form.hidden_field "news_item[link]", value: article['url'] %>
        <%= form.hidden_field "news_item[representative_id]", value: params[:representative_id] %>
        <%= form.hidden_field "news_item[issue]", value: params[:news_item][:issue] %>        <hr>
      </div>
    <% end %>
  </fieldset>
</body>

  <div>
    <%= form.label :"news_item[rating]", 'Rating' %>
    <%= form.select :"news_item[rating]", options_for_select([1, 2, 3, 4, 5]) %>
    
  </div>



  <%= form.submit "Save" %>
<% end %>


      <!-- Add 'View News Articles' button -->
      <%= link_to 'View News Articles', representative_news_items_path(@representative), class: 'btn btn-primary' %>
    </div>
  </div>
</div>